### PR TITLE
Adding pyenv-virtualenv support

### PR DESCRIPTION
**Pull request by leira**
I added pyenv-virtualenv support.

### CODE REVIEW

**Comment by daenney** [comment]
I don't think this should be part of the pyenv plugin. Plenty of people use pyenv on fish without pyenv-virtualenv but instead use virtualfish.

This should be its own plugin.

**Comment by amir20** [comment]
So will this never get merged? What's going on with this PR?

**Comment by daenney** [comment]
I'm not planning on merging it no. Like I said, virtualenv is an extension on it and should just be its own plugin, especially since it can simply specify that it depends on the pyenv plugin.

**Comment by amir20** [comment]
Then you should close this pull request. What's the point of being open.

**Comment by daenney** [comment]
That I forgot about it? Stuff happens.

**Pull request closed without merging**
